apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: metrics-serving-cert
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: zero-trust-workload-identity-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zero-trust-workload-identity-manager
    app.kubernetes.io/part-of: zero-trust-workload-identity-manager
    control-plane: controller-manager
    name: zero-trust-workload-identity-manager
    svc: zero-trust-workload-identity-manager-metrics-service
  name: zero-trust-workload-identity-manager-metrics-service
spec:
  ports:
  - name: metrics-https
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: metrics-http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: zero-trust-workload-identity-manager
status:
  loadBalancer: {}
